# layouts/default.yaml - Simple left/right split
name: "default"
description: "Halves (left/right split)"

# Overlay appearance
overlay:
  color: "cyan"
  opacity: 0.3
  auto_hide_seconds: 3

# Zones apply to ALL monitors by default
zones:
  - name: "left"
    x_percent: 0
    y_percent: 0
    width_percent: 50
    height_percent: 100
    key: "Q"
  
  - name: "right"
    x_percent: 50
    y_percent: 0
    width_percent: 50
    height_percent: 100
    key: "W"