# quarters.yaml - 2x2 grid layout

name: "quarters"
description: "2x2 grid of equal quadrants"

# Overlay appearance
overlay:
  color: "cyan"
  opacity: 0.3
  auto_hide_seconds: 3

zones:
  - name: "top_left"
    x_percent: 0
    y_percent: 0
    width_percent: 50
    height_percent: 50
    respect_taskbar: true
    key: "Q"
  
  - name: "top_right"
    x_percent: 50
    y_percent: 0
    width_percent: 50
    height_percent: 50
    respect_taskbar: true
    key: "W"
  
  - name: "bottom_left"
    x_percent: 0
    y_percent: 50
    width_percent: 50
    height_percent: 50
    respect_taskbar: true
  
  - name: "bottom_right"
    x_percent: 50
    y_percent: 50
    width_percent: 50
    height_percent: 50
    respect_taskbar: true
