# layouts/default.yaml - Simple left/right split
name: "thirds"
description: "Halves (left/right split)"

# Overlay appearance
overlay:
  color: "cyan"
  opacity: 0.3
  auto_hide_seconds: 3

# Zones apply to ALL monitors by default
zones:
  - name: "left"
    x_percent: 0
    y_percent: 0
    width_percent: 33
    height_percent: 100
    key: "A"

  - name: "center"
    x_percent: 33
    y_percent: 0
    width_percent: 33
    height_percent: 100
    key: "S"
  
  - name: "right"
    x_percent: 66
    y_percent: 0
    width_percent: 34
    height_percent: 100
    key: "D"